### ISSUE TITLE
PDF Not Opening

### ISSUE THREAD

**Issue by keshav-42** [arghyawning/my-iiith#1]
When i click on the pdf file it shows me "Unable to render the code block".

![2023-12-23 (1)](https://github.com/arghyawning/my-iiith/assets/149003837/1d660bd2-9df9-4658-a5fa-4297243f2d5a)

**Comment by arghyawning** [comment]
works for me. just reload and it should be fine. if not, download it

**Comment by keshav-42** [comment]
I tried with a VPN, and it opened. I guess something is wrong with my ISP.
